spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3309/springbatch?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
  main:
    allow-bean-definition-overriding: true
  batch:
    job:
      enabled: true
      names: importJob,importJob2

